version: '3.6'
services:
  sam_app:
    build:
      context: .
      dockerfile: SAM.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock